### ISSUE TITLE
API 개발

### ISSUE THREAD

**Issue by hyunayeo** [hyunayeo/memo_re#16]
- [x] 회원 -> 현아
- [x] 도서 -> 현아
- [x] 게시글 -> 한솔
- [x] 위시 리스트 -> 주희
- [x] 리팩토링
- [x] 페이징 & 검색 기능 추가 -> 지수

**Comment by captain-yun** [comment]
테스트코드 짜보기

**Comment by Lyrics109** [comment]
**API 개발 분담**
- [ ]  controller, service, dao 별
- [x] api 명세서에서 분류한 url 별

**Comment by captain-yun** [comment]
#### 도메인 회원, 도서, 게시글, 위시 리스트
- domain 패키지 안에 생성
- lombok 어노테이션 사용 : @Getter, @Setter
![Image](https://github.com/hyunayeo/memo_re/assets/24825985/c74456ca-42ac-4f7c-a127-d8872261861d)
#### domain은 각 테이블과 매핑, dto는 클라이언트 단의 요청과 응답을 고려하여 작성
참고))
![Image](https://github.com/hyunayeo/memo_re/assets/24825985/c9b0c76b-d887-4706-be57-49fb447ed100)

**Comment by Lyrics109** [comment]
[참고자료](https://salmon2.github.io/spring/2021/06/15/spring-board/)

**Comment by hyunayeo** [comment]
패키지 구조
* controller
* dto
* domain
* repository
* service

**Comment by hyunayeo** [comment]
프로젝트 구성 참고
https://github.com/hyunayeo/memo_re/commit/a681a1dfd1ed66ab63583ba3d42c08c8a5c1332a

**Comment by hyunayeo** [comment]
## DB 컬럼명 매핑 snake_case->camelCase 변경
application.properties 에 아래 코드 추가
mybatis.configuration.map-underscore-to-camel-case=true

**Comment by hyunayeo** [comment]
# database

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://192.168.10.250:3306/book_memo_re?
&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
logging.level.com.zaxxer.hikari=TRACE
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

mybatis.configuration.map-underscore-to-camel-case=true

**Comment by captain-yun** [comment]
### api 통합 결과 피드백

- [x] 매핑 URL 변경
    * @GetMapping("/") ->  @GetMapping("")
    * @PostMapping("/join") -> @PostMapping("")
    * @GetMapping("/delete/{id}") ->     @DeleteMapping("/{id}")
- [ ] API 세부 기능 구현 필요 (아래 예시 참고)
![Image](https://github.com/hyunayeo/memo_re/assets/24825985/5035c8c6-295c-4753-ac19-8a5a1235b334)
- [ ] wish_book, wish_article, question API도 추가할 것

**Comment by hyunayeo** [comment]
API Response 구조 설계

- https://stackoverflow.com/questions/12806386/is-there-any-standard-for-json-api-response-format
- https://blog.lyunho.kim/api-response

**Comment by hyunayeo** [comment]
- [x] api url 구조 통일
- [x] 메소드명 통일

**Comment by captain-yun** [comment]
### 페이징 & 검색 기능 추가
* 검색 기능 
* 페이징 기능
* 정렬 기능

#### TODO
- [x] 게시글 검색 기능 추가
- [x] 게시글 페이징 기능 추가
- [x] 게시글 정렬 기능 추가
  - [ ] SearchDto 필드 검증 기능 추가하기
- [ ] 게시글 응답 시 ArticleResponseDto로 변경

#### [ 참고자료 ]
- [마이바티스 SQL Builder 클래스 - 공식 홈페이지](https://mybatis.org/mybatis-3/ko/statement-builders.html)
- [마이바티스 SQL Builder 클래스 - 블로그 참조](https://jason-moon.tistory.com/130)
- [마이바티스 페이징, 검색 - 블로그 참조](https://congsong.tistory.com/26#4.-%EC%84%9C%EB%B9%84%EC%8A%A4service-%EC%88%98%EC%A0%95%ED%95%98%EA%B8%B0)
- [마이바티스 페이징, 검색2 - 블로그 참조](https://congsong.tistory.com/27)
